
backend:
  name: git-gateway
  branch: main # Replace with the name of your branch (usually "main" or "master")

media_folder: "static/images/uploads" # This is where your uploaded images will be stored
public_folder: "/images/uploads"      # This is where your site will reference the images

collections:
  - name: "posts"      # This is for managing blog posts
    label: "Posts"
    folder: "content/posts"   # The folder where your posts will be stored
    create: true
    slug: "{{slug}}"    # How the post URLs will be generated
    fields:             # Define the fields for each post
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
